version: "3"

services:
  cms:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      drupal-modules:/var/www/html/modules \
    -v drupal-profiles:/var/www/html/profiles \
    -v drupal-sites:/var/www/html/sites \
    -v drupal-themes:/var/www/html/themes \
  db:
    image: postgres # this will use httpd:latest
    environment:
      - POSTGRES_PASSWORD=lolcakes

  volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: